# Generated by Django 4.1.1 on 2022-09-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('subscriber', 'subcriber'), ('moderator', 'moderator'), ('regular', 'regular')], default='regular', max_length=100),
        ),
    ]
