# Generated by Django 4.1.1 on 2022-09-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('moderator', 'moderator'), ('regular', 'regular'), ('subscriber', 'subcriber')], default='regular', max_length=100),
        ),
    ]
