# Generated by Django 4.1.1 on 2022-09-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('regular', 'regular'), ('subscriber', 'subcriber'), ('moderator', 'moderator')], default='regular', max_length=100),
        ),
    ]
