# Generated by Django 4.1.1 on 2022-09-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Article'},
        ),
        migrations.AlterModelOptions(
            name='articleseries',
            options={'ordering': ['-published'], 'verbose_name_plural': 'Series'},
        ),
    ]
